### ISSUE TITLE
Stateless URL keeps growing on every Ajax call

### ISSUE THREAD

**Issue by robmcguinness** [jolira/wicket-stateless#1]
**on page load**: home?0-1.ILinkListener-c2--link

**on increment click**: home?0-0.ILinkListener-c2--link&random=0.6425176055241937&counter=1

**on 2nd increment click:** home?0-0.ILinkListener-c2--link&random=0.6425176055241937&random=0.1479492739213617&counter=2

wicket-ajax.js is appending a query parameter 'random' to the get url that needs to be removed.  This can be done in StatelesssEncoder.mergeParameters, **params.remove("random");** but I'm not sure if it's the best solution or if I'm doing something wrong.

**Comment by melocode** [comment]
Hi rob,

I'm new around here.  

I've observed that in addition to appending the random parameter multiple times with each Ajax call, the counter parameter is there always twice as well.

I've implemented this in my own project and one of my custom URL parameters is there twice (just like counter) after two Ajax clicks.  Other than taking up URL parameter space, my getParameter() always seems to get the right one of the two, so my app works OK.

**Comment by robmcguinness** [comment]
lemuellara, were you able to address the issue?  haven't looked at stateless wicket 1.5 in a while.  anyhow, i'm going to be using it again soon and adding pull request to this project to address any issues.

**Comment by melocode** [comment]
Hi Rob,

We still see the same behavior where a new URL parameter is added after each Ajax call, but my application is working OK because the getParameter() always seems to get the latest (correct) one.

I think that your recommendation to call params.remove("random") in the StatelessEncoder is a good one.
